name: cicd_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 23.03.01+230301224255

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter_flavor: 
  youtube_player_flutter: 8.0.0
  pod_player: ^0.0.5
  firebase_analytics: 9.3.3
  firebase_core: 1.21.1
  firebase_crashlytics: 2.8.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  flutter_svg:
  url_launcher:
  fluttertoast: ^8.0.8
  flutter_bloc: ^7.2.0
  freezed_annotation: 1.1.0
  flutter_riverpod: ^1.0.3
  get_it: ^7.2.0
  intl: ^0.17.0
  dropdown_button2: 1.4.0
  buttons_tabbar: ^1.3.1
  package_info_plus: ^1.4.2
  flutter_facebook_sdk: ^1.0.0
  percent_indicator: 4.0.0
  flutter_staggered_grid_view: 0.4.0
  share_plus: ^4.0.10

dependency_overrides:
  youtube_explode_dart: ^1.11.0

dev_dependencies:
  test: any
  freezed: 1.1.0
  flutter_lints:
  build_runner:

flutter:
  uses-material-design: true
