name: Auto bump version

on: 
  # workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  NUMBER: ${{ env.MY_DATE }}

jobs:
  bump_version_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      # 改系統時區
      - name: Setup timezone
        run: sudo timedatectl set-timezone Asia/Taipei
      - name: Get current date
        id: date
      # 取得系統日期 月日年時分
        run: echo "MY_DATE=$(date "+%m%d%y%H%M")" >> $GITHUB_ENV
      # 保存日期至 Environment variable 做使用
      # - name: Environment variable
      #   env:
      #     NUMBER: ${{ env.MY_DATE }}
      # 暫時解法.. 修改第7行'+'以後的小版號
        run: | 
          sed -i '7 s/\+[^,]*$/'+"$NUMBER"'/g' pubspec.yaml
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Automated Change Version Number
  build:
    needs: bump_version_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0
      - run: sed -e '' pubspec.yaml
      - run: echo "$NUMBER"
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: develop
  #         fetch-depth: 0
  #     # - run: git switch -
  #     # - run: git pull
  #     - run: git branch
  #     - name: Setup timezone
  #       run: sudo timedatectl set-timezone Asia/Taipei
  #     - name: Get current date
  #       id: date
  #       run: echo "MY_DATE=$(date "+%y%m%d%H%M%S")" >> $GITHUB_ENV
  #     - name: Environment variable
  #       env:
  #         VERSION: ${{ env.MY_DATE }}
  #       run: | 
  #         sed -i '7 s/\+[^,]*$/'+"$VERSION"'/g' pubspec.yaml
      # - uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Automated Change Version Number
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     commit-message: 版號自動更新
      #     title: Automated Bump Version Number
      #     body: ''
      #     reviewers: MikeChen1109
          
