name: Auto bump version

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      # - run: git checkout HEAD^
      # - run: git pull
      - name: Setup timezone
        run: sudo timedatectl set-timezone Asia/Taipei
      - name: Get current date
        id: date
        run: echo "MY_DATE=$(date "+%y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Environment variable
        env:
          VERSION: ${{ env.MY_DATE }}
        run: | 
          sed -i '7 s/\+[^,]*$/'+"$VERSION"'/g' pubspec.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change Version Number
