name: Auto bump version

on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
          # ref: ${{ github.event.pull_request.head.sha }}
          # fetch-depth: 0
      # - run: git switch -
      # - run: git pull
      - run: git branch
      - name: Setup timezone
        run: sudo timedatectl set-timezone Asia/Taipei
      - name: Get current date
        id: date
        run: echo "MY_DATE=$(date "+%y%m%d%H%M%S")" >> $GITHUB_ENV
      - name: Environment variable
        env:
          VERSION: ${{ env.MY_DATE }}
        run: | 
          sed -i '7 s/\+[^,]*$/'+"$VERSION"'/g' pubspec.yaml
      # - name: Git commit, rebase onto master
      #   env:
      #     PUSH_BRANCH: develop
      #     TMP_BRANCH: ${{ github.repository }}${{ github.run_id}}
      #   run: |
      #     git branch
      #     # git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      #     # git config --local user.name "$GITHUB_ACTOR"
      #     # git checkout -b $TMP_BRANCH
      #     # git add pubspec.yaml
      #     # git commit -m 'Automated Change Version Number' 
      #     # git fetch
      #     # git pull
      #     # git push
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     default_author: github_actions
      #     push: origin HEAD:${{ github.head_ref }}
      #     message: Automated Change Version Number
          # push: origin HEAD:master
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change Version Number
