name: Auto bump version

on: 
  check_run:
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup timezone
        run: sudo timedatectl set-timezone Asia/Taipei
      - name: Get current date
        id: date
        run: echo "MY_DATE=$(date "+%y.%m.%d+%H%M%S")" >> $GITHUB_ENV
      - name: Environment variable
        env:
          VERSION: ${{ env.MY_DATE }}
        run: | 
          sed -i 's/version:.*/version: '"$VERSION"'/g' pubspec.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
