name: Build APK & iOS

on: 
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.5'
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter format --set-exit-if-changed .
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign
